
namespace: notes

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: bodega.cicloinfinito.com:6088/mikeruu/wiki
  newTag: 0a5fc56c5f5a403763d7cdb635fcd108efdbfc9f
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
